# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nbank.proto\"y\n\nInitBranch\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\r\x12(\n\x0c\x61ll_branches\x18\x02 \x03(\x0b\x32\x12.InitBranch.Branch\x1a\x30\n\x06\x42ranch\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"/\n\x08Transfer\x12\x13\n\x0bsend_branch\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\r\"#\n\x0cInitSnapshot\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\r\"2\n\x06Marker\x12\x13\n\x0bsend_branch\x18\x01 \x01(\t\x12\x13\n\x0bsnapshot_id\x18\x02 \x01(\r\"\'\n\x10RetrieveSnapshot\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\r\"\x95\x01\n\x0eReturnSnapshot\x12\x35\n\x0elocal_snapshot\x18\x01 \x01(\x0b\x32\x1d.ReturnSnapshot.LocalSnapshot\x1aL\n\rLocalSnapshot\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\r\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\r\x12\x15\n\rchannel_state\x18\x03 \x03(\r\"\x83\x02\n\rBranchMessage\x12\"\n\x0binit_branch\x18\x01 \x01(\x0b\x32\x0b.InitBranchH\x00\x12\x1d\n\x08transfer\x18\x02 \x01(\x0b\x32\t.TransferH\x00\x12&\n\rinit_snapshot\x18\x03 \x01(\x0b\x32\r.InitSnapshotH\x00\x12\x19\n\x06marker\x18\x04 \x01(\x0b\x32\x07.MarkerH\x00\x12.\n\x11retrieve_snapshot\x18\x05 \x01(\x0b\x32\x11.RetrieveSnapshotH\x00\x12*\n\x0freturn_snapshot\x18\x06 \x01(\x0b\x32\x0f.ReturnSnapshotH\x00\x42\x10\n\x0e\x62ranch_messageb\x06proto3')
)




_INITBRANCH_BRANCH = _descriptor.Descriptor(
  name='Branch',
  full_name='InitBranch.Branch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='InitBranch.Branch.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='InitBranch.Branch.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='InitBranch.Branch.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=135,
)

_INITBRANCH = _descriptor.Descriptor(
  name='InitBranch',
  full_name='InitBranch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='InitBranch.balance', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_branches', full_name='InitBranch.all_branches', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INITBRANCH_BRANCH, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=135,
)


_TRANSFER = _descriptor.Descriptor(
  name='Transfer',
  full_name='Transfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='send_branch', full_name='Transfer.send_branch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Transfer.amount', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=184,
)


_INITSNAPSHOT = _descriptor.Descriptor(
  name='InitSnapshot',
  full_name='InitSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='InitSnapshot.snapshot_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=221,
)


_MARKER = _descriptor.Descriptor(
  name='Marker',
  full_name='Marker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='send_branch', full_name='Marker.send_branch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='Marker.snapshot_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=273,
)


_RETRIEVESNAPSHOT = _descriptor.Descriptor(
  name='RetrieveSnapshot',
  full_name='RetrieveSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='RetrieveSnapshot.snapshot_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=314,
)


_RETURNSNAPSHOT_LOCALSNAPSHOT = _descriptor.Descriptor(
  name='LocalSnapshot',
  full_name='ReturnSnapshot.LocalSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_id', full_name='ReturnSnapshot.LocalSnapshot.snapshot_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='ReturnSnapshot.LocalSnapshot.balance', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_state', full_name='ReturnSnapshot.LocalSnapshot.channel_state', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=466,
)

_RETURNSNAPSHOT = _descriptor.Descriptor(
  name='ReturnSnapshot',
  full_name='ReturnSnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_snapshot', full_name='ReturnSnapshot.local_snapshot', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RETURNSNAPSHOT_LOCALSNAPSHOT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=466,
)


_BRANCHMESSAGE = _descriptor.Descriptor(
  name='BranchMessage',
  full_name='BranchMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='init_branch', full_name='BranchMessage.init_branch', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transfer', full_name='BranchMessage.transfer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init_snapshot', full_name='BranchMessage.init_snapshot', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marker', full_name='BranchMessage.marker', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retrieve_snapshot', full_name='BranchMessage.retrieve_snapshot', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_snapshot', full_name='BranchMessage.return_snapshot', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='branch_message', full_name='BranchMessage.branch_message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=469,
  serialized_end=728,
)

_INITBRANCH_BRANCH.containing_type = _INITBRANCH
_INITBRANCH.fields_by_name['all_branches'].message_type = _INITBRANCH_BRANCH
_RETURNSNAPSHOT_LOCALSNAPSHOT.containing_type = _RETURNSNAPSHOT
_RETURNSNAPSHOT.fields_by_name['local_snapshot'].message_type = _RETURNSNAPSHOT_LOCALSNAPSHOT
_BRANCHMESSAGE.fields_by_name['init_branch'].message_type = _INITBRANCH
_BRANCHMESSAGE.fields_by_name['transfer'].message_type = _TRANSFER
_BRANCHMESSAGE.fields_by_name['init_snapshot'].message_type = _INITSNAPSHOT
_BRANCHMESSAGE.fields_by_name['marker'].message_type = _MARKER
_BRANCHMESSAGE.fields_by_name['retrieve_snapshot'].message_type = _RETRIEVESNAPSHOT
_BRANCHMESSAGE.fields_by_name['return_snapshot'].message_type = _RETURNSNAPSHOT
_BRANCHMESSAGE.oneofs_by_name['branch_message'].fields.append(
  _BRANCHMESSAGE.fields_by_name['init_branch'])
_BRANCHMESSAGE.fields_by_name['init_branch'].containing_oneof = _BRANCHMESSAGE.oneofs_by_name['branch_message']
_BRANCHMESSAGE.oneofs_by_name['branch_message'].fields.append(
  _BRANCHMESSAGE.fields_by_name['transfer'])
_BRANCHMESSAGE.fields_by_name['transfer'].containing_oneof = _BRANCHMESSAGE.oneofs_by_name['branch_message']
_BRANCHMESSAGE.oneofs_by_name['branch_message'].fields.append(
  _BRANCHMESSAGE.fields_by_name['init_snapshot'])
_BRANCHMESSAGE.fields_by_name['init_snapshot'].containing_oneof = _BRANCHMESSAGE.oneofs_by_name['branch_message']
_BRANCHMESSAGE.oneofs_by_name['branch_message'].fields.append(
  _BRANCHMESSAGE.fields_by_name['marker'])
_BRANCHMESSAGE.fields_by_name['marker'].containing_oneof = _BRANCHMESSAGE.oneofs_by_name['branch_message']
_BRANCHMESSAGE.oneofs_by_name['branch_message'].fields.append(
  _BRANCHMESSAGE.fields_by_name['retrieve_snapshot'])
_BRANCHMESSAGE.fields_by_name['retrieve_snapshot'].containing_oneof = _BRANCHMESSAGE.oneofs_by_name['branch_message']
_BRANCHMESSAGE.oneofs_by_name['branch_message'].fields.append(
  _BRANCHMESSAGE.fields_by_name['return_snapshot'])
_BRANCHMESSAGE.fields_by_name['return_snapshot'].containing_oneof = _BRANCHMESSAGE.oneofs_by_name['branch_message']
DESCRIPTOR.message_types_by_name['InitBranch'] = _INITBRANCH
DESCRIPTOR.message_types_by_name['Transfer'] = _TRANSFER
DESCRIPTOR.message_types_by_name['InitSnapshot'] = _INITSNAPSHOT
DESCRIPTOR.message_types_by_name['Marker'] = _MARKER
DESCRIPTOR.message_types_by_name['RetrieveSnapshot'] = _RETRIEVESNAPSHOT
DESCRIPTOR.message_types_by_name['ReturnSnapshot'] = _RETURNSNAPSHOT
DESCRIPTOR.message_types_by_name['BranchMessage'] = _BRANCHMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitBranch = _reflection.GeneratedProtocolMessageType('InitBranch', (_message.Message,), dict(

  Branch = _reflection.GeneratedProtocolMessageType('Branch', (_message.Message,), dict(
    DESCRIPTOR = _INITBRANCH_BRANCH,
    __module__ = 'bank_pb2'
    # @@protoc_insertion_point(class_scope:InitBranch.Branch)
    ))
  ,
  DESCRIPTOR = _INITBRANCH,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:InitBranch)
  ))
_sym_db.RegisterMessage(InitBranch)
_sym_db.RegisterMessage(InitBranch.Branch)

Transfer = _reflection.GeneratedProtocolMessageType('Transfer', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFER,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:Transfer)
  ))
_sym_db.RegisterMessage(Transfer)

InitSnapshot = _reflection.GeneratedProtocolMessageType('InitSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _INITSNAPSHOT,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:InitSnapshot)
  ))
_sym_db.RegisterMessage(InitSnapshot)

Marker = _reflection.GeneratedProtocolMessageType('Marker', (_message.Message,), dict(
  DESCRIPTOR = _MARKER,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:Marker)
  ))
_sym_db.RegisterMessage(Marker)

RetrieveSnapshot = _reflection.GeneratedProtocolMessageType('RetrieveSnapshot', (_message.Message,), dict(
  DESCRIPTOR = _RETRIEVESNAPSHOT,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:RetrieveSnapshot)
  ))
_sym_db.RegisterMessage(RetrieveSnapshot)

ReturnSnapshot = _reflection.GeneratedProtocolMessageType('ReturnSnapshot', (_message.Message,), dict(

  LocalSnapshot = _reflection.GeneratedProtocolMessageType('LocalSnapshot', (_message.Message,), dict(
    DESCRIPTOR = _RETURNSNAPSHOT_LOCALSNAPSHOT,
    __module__ = 'bank_pb2'
    # @@protoc_insertion_point(class_scope:ReturnSnapshot.LocalSnapshot)
    ))
  ,
  DESCRIPTOR = _RETURNSNAPSHOT,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:ReturnSnapshot)
  ))
_sym_db.RegisterMessage(ReturnSnapshot)
_sym_db.RegisterMessage(ReturnSnapshot.LocalSnapshot)

BranchMessage = _reflection.GeneratedProtocolMessageType('BranchMessage', (_message.Message,), dict(
  DESCRIPTOR = _BRANCHMESSAGE,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:BranchMessage)
  ))
_sym_db.RegisterMessage(BranchMessage)


# @@protoc_insertion_point(module_scope)
